server:
  port: 8081
  servlet:
    context-path: /

spring:
  h2:
    console:
      enabled: true

  devtools:
    livereload:
      enabled: true

  jpa:
    database: H2

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassname: org.h2.Driver