user:
  email: ydhwa@test
  nickname: ydh
  age: 24
  auth: false
  amount: 100

spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    data: classpath:init.sql    # 시작할 때 실행시킬 script

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false



logging:
  level:
    root: info
